name: Deploy Backend

on:
    push:
        paths:
        - 'src/backend/*'    
        - '.github/workflows/deploy-backend.yml'
    workflow_dispatch:   

env:
  AZURE_WEBAPP_NAME: ${{ secrets.BACK_END_NAME }}    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '/src/backend'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main

      - name: Azure Login
        uses: Azure/login@v2        
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      
      - name: logout
        run: |
          az logout